"""Drives the /banner scenario pipeline for one TG session.

Unlike /new (graph_runner), /banner has NO LLM, no persona/eval, no
LangGraph — it is a straight line:

    collect slot texts + hero  ->  (optional) Phygital remove-bg cutout
    ->  render every format of the scenario  ->  ZIP + media-group delivery

The hero is supplied by the user (upload) or generated by @Cloud_Phygital_bot.
When the scenario's HeroPolicy.remove_bg is set and USE_PHYGITAL_RENDER is on,
the hero is run through Phygital's standalone remove-background path so the
cutout drops onto the green panel without a box.
"""

from __future__ import annotations

import asyncio
import secrets
import time
from datetime import datetime
from pathlib import Path

import structlog
from telegram import InputMediaPhoto
from telegram.ext import Application

from bot.config import get_settings
from bot.graph_runner import B2B_PENDING_KEY, B2BError, _b2b_progress_task
from bot.sessions import Session, drop, put
from infra.banner_render import build_zip, load_banner_manifest, render_scenario

log = structlog.get_logger(__name__)

_BANNER_OUT = Path("/data/banners")
_HEROES_DIR = Path("/data/heroes")
# Keep concurrent Phygital remove-bg requests modest — their semaphore is 4,
# we stay under it (one banner session sends one removebg at a time anyway).
_REMOVEBG_SEMAPHORE = asyncio.Semaphore(3)


async def request_removebg(
    app: Application, session: Session, image_bytes: bytes
) -> bytes:
    """Standalone Phygital remove-background.

    Sends the hero as a Document (NOT a photo — TG would JPEG-flatten the
    alpha) with caption ``@b2b removebg corr=<hex>`` and waits for the
    reply Document (PNG with alpha). Returns the cutout PNG bytes.

    Raises B2BError on an ``@b2b ERROR`` reply or asyncio.TimeoutError if the
    Phygital bot doesn't answer in time. Caller decides the fallback (use the
    original hero as-is).
    """
    settings = get_settings()
    corr = secrets.token_hex(4)
    pending = app.bot_data.setdefault(B2B_PENDING_KEY, {})
    loop = asyncio.get_running_loop()
    fut: asyncio.Future[bytes] = loop.create_future()
    pending[corr] = {
        "future": fut,
        "thread_id": session.thread_id,
        "user_id": session.user_id,
    }
    target = f"@{settings.phygital_bot_username}"
    started = time.monotonic()
    async with _REMOVEBG_SEMAPHORE:
        try:
            await app.bot.send_document(
                chat_id=target,
                document=image_bytes,
                filename="hero.png",
                caption=f"@b2b removebg corr={corr}",
            )
            log.info("b2b_removebg_sent", thread_id=session.thread_id, corr=corr)
            return await asyncio.wait_for(
                fut, timeout=settings.phygital_request_timeout_s
            )
        finally:
            pending.pop(corr, None)
            log.info(
                "b2b_removebg_done",
                thread_id=session.thread_id,
                corr=corr,
                elapsed_ms=int((time.monotonic() - started) * 1000),
            )


def _formats_need_cutout(manifest, scenario_id: str, formats: list[str] | None) -> bool:
    """True if any rendered format has a hero_cutout layer (remove-bg only makes
    sense for cutouts — a framed cover photo, e.g. SMM 'visual', keeps its bg)."""
    from infra.template_manifest import HeroCutoutLayer

    fmts = formats or manifest.scenarios[scenario_id].formats
    for f in fmts:
        if any(isinstance(l, HeroCutoutLayer) for l in manifest.templates[f].layers):
            return True
    return False


async def request_generate_cutout(
    app: Application, session: Session, prompt: str
) -> bytes:
    """Chained Phygital generate + remove-bg (rmbg=1).

    One request — ``@b2b render 3:4 k2 rmbg=1 corr=<hex>\\n\\n<prompt>`` — and
    Phygital runs the generated image through Photoroom before replying with a
    Document (PNG with alpha). Returns the cutout bytes.
    """
    settings = get_settings()
    corr = secrets.token_hex(4)
    pending = app.bot_data.setdefault(B2B_PENDING_KEY, {})
    loop = asyncio.get_running_loop()
    fut: asyncio.Future[bytes] = loop.create_future()
    pending[corr] = {
        "future": fut,
        "thread_id": session.thread_id,
        "user_id": session.user_id,
    }
    target = f"@{settings.phygital_bot_username}"
    started = time.monotonic()
    async with _REMOVEBG_SEMAPHORE:
        try:
            await app.bot.send_message(
                chat_id=target,
                text=f"@b2b render 3:4 k2 rmbg=1 corr={corr}\n\n{prompt}",
            )
            log.info("b2b_gen_cutout_sent", thread_id=session.thread_id, corr=corr)
            return await asyncio.wait_for(
                fut, timeout=settings.phygital_request_timeout_s
            )
        finally:
            pending.pop(corr, None)
            log.info(
                "b2b_gen_cutout_done",
                thread_id=session.thread_id,
                corr=corr,
                elapsed_ms=int((time.monotonic() - started) * 1000),
            )


async def run_banner(app: Application, session: Session) -> None:
    """Render the chosen scenario from collected texts + hero, deliver ZIP.

    Reads from session.wizard_data:
      - scenario_id: str
      - texts: dict[str, str]
      - hero_path: str | None  (None for hero-less text covers)
      - formats: list[str] | None  (subset, e.g. one SMM archetype)
    """
    wd = session.wizard_data
    scenario_id = wd["scenario_id"]
    texts: dict[str, str] = wd.get("texts", {})
    hero_path: str | None = wd.get("hero_path")
    gen_prompt: str | None = wd.get("gen_prompt")
    formats: list[str] | None = wd.get("formats")

    manifest = load_banner_manifest()
    scenario = manifest.scenarios[scenario_id]

    hero_bytes: bytes | None = None
    if gen_prompt:
        # Generated hero already comes back as a remove-bg cutout (rmbg=1).
        try:
            hero_bytes = await request_generate_cutout(app, session, gen_prompt)
        except Exception as exc:  # noqa: BLE001
            reason = getattr(exc, "reason", type(exc).__name__)
            log.warning("gen_cutout_failed", thread_id=session.thread_id, reason=reason)
            await app.bot.send_message(
                chat_id=session.chat_id,
                text=(
                    f"Не удалось сгенерировать картинку ({reason}). "
                    "Запусти /banner и загрузи изображение вручную."
                ),
            )
            drop(app.bot_data, session.user_id)
            return
    elif hero_path:
        hero_bytes = Path(hero_path).read_bytes()
        if (
            scenario.hero is not None
            and scenario.hero.remove_bg
            and _formats_need_cutout(manifest, scenario_id, formats)
        ):
            hero_bytes = await _maybe_removebg(app, session, hero_bytes)

    out_dir = _BANNER_OUT / session.thread_id
    try:
        files = await render_scenario(
            scenario_id=scenario_id,
            hero=hero_bytes,
            texts=texts,
            out_dir=out_dir,
            session_id=session.thread_id,
            manifest=manifest,
            formats=formats,
        )
    except Exception as exc:  # noqa: BLE001
        log.exception("banner_render_failed", thread_id=session.thread_id)
        await app.bot.send_message(
            chat_id=session.chat_id,
            text=f"Сбой рендера баннеров: {type(exc).__name__}. Попробуй /banner заново.",
        )
        drop(app.bot_data, session.user_id)
        return

    if not files:
        await app.bot.send_message(
            chat_id=session.chat_id,
            text="Ни один формат не отрендерился. Проверь, что выбран сценарий и заданы тексты.",
        )
        drop(app.bot_data, session.user_id)
        return

    ts = datetime.utcnow().strftime("%Y%m%dT%H%M%S")
    zip_path = out_dir / f"{scenario_id}_{ts}.zip"
    await build_zip(files, zip_path)
    await _deliver(app, session, scenario, files, zip_path)
    session.status = "done"
    put(app.bot_data, session)
    drop(app.bot_data, session.user_id)


async def _maybe_removebg(
    app: Application, session: Session, hero_bytes: bytes
) -> bytes:
    """Run the hero through Phygital remove-bg if enabled; on any failure fall
    back to the original bytes (the composer will still place it, just with its
    own background)."""
    settings = get_settings()
    if not settings.use_phygital_render:
        return hero_bytes
    status = await app.bot.send_message(
        chat_id=session.chat_id,
        text=(
            "Убираю фон у изображения через @"
            f"{settings.phygital_bot_username}… "
            f"до {settings.phygital_request_timeout_s // 60} мин."
        ),
    )
    progress = _b2b_progress_task(
        app, session.chat_id, status.message_id, time.monotonic(),
        settings.phygital_request_timeout_s,
    )
    try:
        cutout = await request_removebg(app, session, hero_bytes)
    except (B2BError, asyncio.TimeoutError) as exc:
        reason = getattr(exc, "reason", type(exc).__name__)
        log.warning("removebg_fallback", thread_id=session.thread_id, reason=reason)
        await app.bot.send_message(
            chat_id=session.chat_id,
            text=(
                f"Не удалось убрать фон ({reason}). "
                "Использую картинку как есть."
            ),
        )
        return hero_bytes
    finally:
        progress.cancel()
    # Persist the cutout next to the heroes for debugging/repro.
    try:
        _HEROES_DIR.mkdir(parents=True, exist_ok=True)
        ts = datetime.utcnow().strftime("%Y%m%dT%H%M%S")
        (_HEROES_DIR / f"{session.thread_id}_{ts}_cutout.png").write_bytes(cutout)
    except Exception as exc:  # noqa: BLE001
        log.debug("cutout_persist_failed", error=str(exc))
    return cutout


async def _deliver(app, session, scenario, files, zip_path: Path) -> None:
    """Send a media-group preview (TG cap 10/group) then the full ZIP."""
    caption = (
        f"{scenario.title}\n"
        f"Форматов: {len(files)}"
    )
    try:
        for start in range(0, len(files), 10):
            batch = files[start : start + 10]
            opened: list = []
            media: list[InputMediaPhoto] = []
            try:
                for i, rec in enumerate(batch):
                    fp = open(rec["path"], "rb")
                    opened.append(fp)
                    cap = caption if (start == 0 and i == 0) else None
                    media.append(InputMediaPhoto(media=fp, caption=cap))
                await app.bot.send_media_group(chat_id=session.chat_id, media=media)
            finally:
                for fp in opened:
                    fp.close()
    except Exception as exc:  # noqa: BLE001
        log.exception("banner_media_group_failed", thread_id=session.thread_id)
        await app.bot.send_message(
            chat_id=session.chat_id,
            text=f"Превью не отправилось ({type(exc).__name__}), ZIP ниже.",
        )

    try:
        with open(zip_path, "rb") as fh:
            await app.bot.send_document(
                chat_id=session.chat_id,
                document=fh,
                filename=zip_path.name,
                caption="Все форматы одним архивом.",
            )
    except Exception as exc:  # noqa: BLE001
        log.exception("banner_zip_send_failed", thread_id=session.thread_id)
        await app.bot.send_message(
            chat_id=session.chat_id,
            text=f"ZIP собран, но отправка не удалась: {type(exc).__name__}. Путь: {zip_path}",
        )
